#!/bin/bash

# Delete the link to the binary
if type update-alternatives >/dev/null 2>&1; then
    update-alternatives --remove 'penguinmod-desktop' '/usr/bin/penguinmod-desktop'
else
    rm -f '/usr/bin/penguinmod-desktop'
fi
