#!/bin/bash

if type update-alternatives 2>/dev/null >&1; then
    # Remove previous link if it doesn't use update-alternatives
    if [ -L '/usr/bin/penguinmod-desktop' -a -e '/usr/bin/penguinmod-desktop' -a "`readlink '/usr/bin/penguinmod-desktop'`" != '/etc/alternatives/penguinmod-desktop' ]; then
        rm -f '/usr/bin/penguinmod-desktop'
    fi
    update-alternatives --install '/usr/bin/penguinmod-desktop' 'penguinmod-desktop' '/opt/PenguinMod/penguinmod-desktop' 100 || ln -sf '/opt/PenguinMod/penguinmod-desktop' '/usr/bin/penguinmod-desktop'
else
    ln -sf '/opt/PenguinMod/penguinmod-desktop' '/usr/bin/penguinmod-desktop'
fi

# Check if user namespaces are supported by the kernel and working with a quick test:
if ! { [[ -L /proc/self/ns/user ]] && unshare --user true; }; then
    # Use SUID chrome-sandbox only on systems without user namespaces:
    chmod 4755 '/opt/PenguinMod/chrome-sandbox' || true
else
    chmod 0755 '/opt/PenguinMod/chrome-sandbox' || true
fi

if hash update-mime-database 2>/dev/null; then
    update-mime-database /usr/share/mime || true
fi

if hash update-desktop-database 2>/dev/null; then
    update-desktop-database /usr/share/applications || true
fi
